
version: 2
sources:
  - name: datafeed_shared_schema
    database: "{{('NYOM')}}"
    schema: SOURCE_LAYER

    tables:
      - name: STUDENTS
      - name: STUDENTS_MAY
      - name: STUDENTS_JUNE
      - name: NEXT_DEP
      - name: PREV_DEP
      - name: department
      - name: customers
        columns:
             
          - name: id
            tests:
              - unique
              - not_null
          - name: full_name
            tests:
              - accepted_values:
                  values: ['Odilia Seti', 'Rishikesh', 'bala','Lewiss MacDwyer']

 
