
version: 2
sources:
  - name: datafeed_shared_schema
    database: "{{('NYOM')}}"
    schema: SOURCE_LAYER

    tables:
      - name: STUDENTS
      - name: STUDENTS_MAY
      - name: STUDENTS_JUNE
      - name: NEXT_DEP
      - name: PREV_DEP

